# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, db_column='SecondName', max_length=50, null=True, verbose_name='Отчество')),
                ('surname', models.CharField(db_column='Surname', max_length=50, verbose_name='Фамилия')),
                ('birthday', models.DateField(db_column='Birthday', verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('M', 'Men'), ('W', 'Women')], db_column='Sex', default='M', max_length=1, verbose_name='Пол')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='participants',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
    ]
