# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_auto_20170926_1748'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participant',
            table='participants',
        ),
    ]
