# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_auto_20170926_1801'),
    ]

    operations = [
    ]
